
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: 1.18.2
  // Integration: webchat
  // Version: 0.3.0
  // File: webchat/channels.ts
  // Hash: 7be95622b732c7a706aeaee9efd6ae18916c01c64cdda539c2659e89f8bf7930
  // Updated at: 2026-04-01T17:04:55.682Z
  ////////////////////////////////////////////////////////

  export type Integration_Channels_Webchat = {
    /**
 * Title: channel
 * Description: No description
 */
    "channel": {
      conversation: {
        tags: {/**
 * Title: undefined
 * Description: undefined
 */
["webchat:id"]?: string,
/**
 * Title: undefined
 * Description: undefined
 */
["webchat:owner"]?: string,
};
      };
      message: {
        tags: {/**
 * Title: undefined
 * Description: undefined
 */
["webchat:feedbackComment"]?: string,
/**
 * Title: undefined
 * Description: undefined
 */
["webchat:feedbackValue"]?: string,
/**
 * Title: undefined
 * Description: undefined
 */
["webchat:id"]?: string,
/**
 * Title: undefined
 * Description: undefined
 */
["webchat:replyTo"]?: string,
/**
 * Title: undefined
 * Description: undefined
 */
["webchat:selectedBy"]?: string,
};
      };
      messages: {
"bloc": { 
/** Fake User ID; allows the bot to pretend sending the message as someone else. */
userId?: string
; items: Array<
{ type: 'text'; payload: { 
/** Fake User ID; allows the bot to pretend sending the message as someone else. */
userId?: string
; text: string; value?: string } } | { type: 'markdown'; payload: { 
/** Fake User ID; allows the bot to pretend sending the message as someone else. */
userId?: string
; markdown: string } } | { type: 'image'; payload: { 
/** Fake User ID; allows the bot to pretend sending the message as someone else. */
userId?: string
; imageUrl: string } } | { type: 'audio'; payload: { 
/** Fake User ID; allows the bot to pretend sending the message as someone else. */
userId?: string
; audioUrl: string } } | { type: 'video'; payload: { 
/** Fake User ID; allows the bot to pretend sending the message as someone else. */
userId?: string
; videoUrl: string } } | { type: 'file'; payload: { 
/** Fake User ID; allows the bot to pretend sending the message as someone else. */
userId?: string
; fileUrl: string; title?: string } } | { type: 'location'; payload: { 
/** Fake User ID; allows the bot to pretend sending the message as someone else. */
userId?: string
; latitude: number; longitude: number; address?: string; title?: string } }>; 
/** Type of the message; same as the top level message type */
type?: string
; metadata?:  { [key: string]: any } };

"video": { 
/** Fake User ID; allows the bot to pretend sending the message as someone else. */
userId?: string
; videoUrl: string; 
/** Type of the message; same as the top level message type */
type?: string
; metadata?:  { [key: string]: any } };

"text": { 
/** Fake User ID; allows the bot to pretend sending the message as someone else. */
userId?: string
; text: string; value?: string; 
/** Type of the message; same as the top level message type */
type?: string
; metadata?:  { [key: string]: any } };

"markdown": { 
/** Fake User ID; allows the bot to pretend sending the message as someone else. */
userId?: string
; markdown: string; 
/** Type of the message; same as the top level message type */
type?: string
; metadata?:  { [key: string]: any } };

"location": { 
/** Fake User ID; allows the bot to pretend sending the message as someone else. */
userId?: string
; latitude: number; longitude: number; address?: string; title?: string; 
/** Type of the message; same as the top level message type */
type?: string
; metadata?:  { [key: string]: any } };

"image": { 
/** Fake User ID; allows the bot to pretend sending the message as someone else. */
userId?: string
; imageUrl: string; 
/** Type of the message; same as the top level message type */
type?: string
; metadata?:  { [key: string]: any } };

"file": { 
/** Fake User ID; allows the bot to pretend sending the message as someone else. */
userId?: string
; fileUrl: string; title?: string; 
/** Type of the message; same as the top level message type */
type?: string
; metadata?:  { [key: string]: any } };

"dropdown": { 
/** Fake User ID; allows the bot to pretend sending the message as someone else. */
userId?: string
; text: string; options: Array<{ label: string; value: string }>; disableFreeText?: boolean; 
/** Type of the message; same as the top level message type */
type?: string
; metadata?:  { [key: string]: any } };

"choice": { 
/** Fake User ID; allows the bot to pretend sending the message as someone else. */
userId?: string
; text: string; options: Array<{ label: string; value: string }>; disableFreeText?: boolean; 
/** Type of the message; same as the top level message type */
type?: string
; metadata?:  { [key: string]: any } };

"carousel": { 
/** Fake User ID; allows the bot to pretend sending the message as someone else. */
userId?: string
; items: Array<{ 
/** Fake User ID; allows the bot to pretend sending the message as someone else. */
userId?: string
; title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }> }>; 
/** Type of the message; same as the top level message type */
type?: string
; metadata?:  { [key: string]: any } };

"card": { 
/** Fake User ID; allows the bot to pretend sending the message as someone else. */
userId?: string
; title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }>; 
/** Type of the message; same as the top level message type */
type?: string
; metadata?:  { [key: string]: any } };

"audio": { 
/** Fake User ID; allows the bot to pretend sending the message as someone else. */
userId?: string
; audioUrl: string; 
/** Type of the message; same as the top level message type */
type?: string
; metadata?:  { [key: string]: any } };

"custom": { 
/** Fake User ID; allows the bot to pretend sending the message as someone else. */
userId?: string
; url: string; name: string; data?: any; 
/** Type of the message; same as the top level message type */
type?: string
; metadata?:  { [key: string]: any } };

      };
    },
  };
  