
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: 1.18.2
  // Integration: webchat
  // Version: 0.3.0
  // File: webchat/configurations.ts
  // Hash: 7be95622b732c7a706aeaee9efd6ae18916c01c64cdda539c2659e89f8bf7930
  // Updated at: 2026-04-01T17:04:55.682Z
  ////////////////////////////////////////////////////////

  export type Integration_Configurations_Webchat = {
  /**
     * @title Default
     * Default configuration
     */
  default: { 
/** The JWT public key used to verify tokens. When specified, userData and attributes in createUser and updateUser should be signed JWT tokens. */
jwtPublicKey?: string
; 
/** The secret key required to manage users */
adminSecret?: string
; version?: string; botDisplayName?: string; botAvatarUrl?: string; botDescription?: string; fabImage?: string; descriptionPhoneNumber?: { title?: string; link?: string }; descriptionEmailAddress?: { title?: string; link?: string }; descriptionWebsiteUrl?: { title?: string; link?: string }; termsConditionsUrl?: { title?: string; link?: string }; privacyPolicyUrl?: { title?: string; link?: string }; botComposerPlaceholder?: string; showPoweredByBotpress?: boolean; additionalStylesheet?: string; additionalStylesheetUrl?: string; allowedOrigins?: string[]; primaryColor?: string; borderRadiusScale?: number; themeMode?: 'light' | 'dark'; variant?: 'solid' | 'soft'; headerVariant?: 'solid' | 'glass'; fontFamily?: string; feedbackEnabled?: boolean; showPoweredBy?: boolean; footer?: string; allowFileUpload?: boolean; storageLocation?: 'sessionStorage' | 'localStorage'; soundEnabled?: boolean; toggleChatId?: string; embeddedChatId?: string; proactiveMessageEnabled?: boolean; proactiveBubbleMessage?: string; proactiveBubbleTriggerType?: 'afterDelay' | 'userIdle'; proactiveBubbleDelayTime?: number; conversationHistory?: boolean; _debug?: boolean };
};