
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: 1.18.2
  // Integration: webchat
  // Version: 0.3.0
  // File: webchat/index.ts
  // Hash: 7be95622b732c7a706aeaee9efd6ae18916c01c64cdda539c2659e89f8bf7930
  // Updated at: 2026-04-01T17:04:55.682Z
  ////////////////////////////////////////////////////////

  import { Integration_Actions_Webchat } from "./actions";
  import { Integration_Channels_Webchat } from "./channels";
  import { Integration_Events_Webchat } from "./events";
  import { Integration_Users_Webchat } from "./users";
  import { Integration_Configurations_Webchat } from "./configurations";

  export * from "./actions";
  export * from "./channels";
  export * from "./events";
  export * from "./users";
  export * from "./configurations";

  export type Integration_All_Webchat = {
    actions: Integration_Actions_Webchat;
    channels: Integration_Channels_Webchat;
    events: Integration_Events_Webchat;
    users: Integration_Users_Webchat;
    configurations: Integration_Configurations_Webchat;
  };
  