
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: 1.18.2
  // Integration: webchat
  // Version: 0.3.0
  // File: webchat/users.ts
  // Hash: 7be95622b732c7a706aeaee9efd6ae18916c01c64cdda539c2659e89f8bf7930
  // Updated at: 2026-04-01T17:04:55.682Z
  ////////////////////////////////////////////////////////

  export type Integration_Users_Webchat = {
    tags: /**
 * Title: undefined
 * Description: undefined
 */
"webchat:id"
;
  };
  