
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: 1.18.2
  // Integration: discord
  // Version: 1.1.0
  // File: discord\actions.ts
  // Hash: 2459abd2e0b561675ce4ccd3fb58bed92316af5a8726ab65752e2ba09625a4c5
  // Updated at: 2026-04-28T21:25:47.689Z
  ////////////////////////////////////////////////////////

  export type Integration_Actions_Discord = {
    /**
 * Title: Add Member Role
 * Description: Add a role to a guild member
 */
    "addMemberRole": {
      input: { 
/** The ID of the guild */
guildId: string
; 
/** The ID of the user */
userId: string
; 
/** The ID of the role to add */
roleId: string
; 
/** Reason for adding the role (appears in audit log) */
reason?: string
 };
      output: {  };
    },

    /**
 * Title: Add Reaction
 * Description: Create a reaction for the message
 */
    "addReaction": {
      input: { 
/** The id of the channel */
channelId: string
; 
/** The id of the message */
messageId: string
; 
/** Can be either the actual emoji or its id */
emoji: string
 };
      output: {  };
    },

    /**
 * Title: Ban User
 * Description: Ban a user from a guild
 */
    "banUser": {
      input: { 
/** The ID of the guild */
guildId: string
; 
/** The ID of the user to ban */
userId: string
; 
/** Number of seconds of messages to delete (0-604800) */
deleteMessageSeconds?: number
; 
/** Reason for the ban (appears in audit log) */
reason?: string
 };
      output: {  };
    },

    /**
 * Title: Call API
 * Description: Send a raw HTTP request to any Discord API endpoint
 */
    "callApi": {
      input: { 
/** The API path (e.g. /channels/123/messages) */
path: string
; 
/** The query parameters to send along with the request */
queryParams?: Array<{ key: string; value: string }>
; 
/** The HTTP method to use */
method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'
; 
/** JSON string to send as the request body */
body?: string
 };
      output: { 
/** Whether the request was successful */
success: boolean
; 
/** The response body as an object if the request was successful */
body?: any
; 
/** The error message if the request was not successful */
error?: string
; 
/** The HTTP status code of the response */
status?: number
 };
    },

    /**
 * Title: Create Channel
 * Description: Creates a new channel in a guild.
 */
    "createChannel": {
      input: { 
/** The ID of the guild to create the channel in */
guildId: string
; 
/** The name of the channel */
name: string
; 
/** Channel type. Defaults to Guild Text (0). */
type?: number
; 
/** Channel topic */
topic?: string
; 
/** Sorting position of the channel */
position?: number
; 
/** Whether the channel is NSFW */
nsfw?: boolean
; 
/** ID of the parent category */
parentId?: string
 };
      output: { 
/** Channel ID */
id: string
; 
/** Channel type */
type: number
; 
/** Channel name */
name?: string
; 
/** Sorting position of the channel */
position?: number
; 
/** ID of the parent category */
parentId?: string | null
; 
/** Channel topic */
topic?: string | null
; 
/** Whether the channel is NSFW */
nsfw?: boolean
 };
    },

    /**
 * Title: Create Poll
 * Description: Creates a poll in a Discord channel.
 */
    "createPoll": {
      input: { 
/** The ID of the channel to create the poll in */
channelId: string
; 
/** The question of the poll */
question: string
; 
/** The answers available in the poll (1-10) */
answers: Array<{ 
/** The text of the answer */
text: string
; 
/** An optional emoji for the answer */
emoji?: string
 }>
; 
/** Number of hours the poll should be open for, up to 768 (32 days). Defaults to 24 */
duration?: number
; 
/** Whether a user can select multiple answers. Defaults to false */
allowMultiselect?: boolean
 };
      output: { 
/** The ID of the message containing the poll */
messageId: string
; 
/** The poll answers with their Discord-assigned IDs */
answers: Array<{ 
/** The ID of the answer */
answerId: number
; 
/** The answer text */
text: string
 }>
 };
    },

    /**
 * Title: Create Role
 * Description: Create a new role in a guild
 */
    "createRole": {
      input: { 
/** The ID of the guild */
guildId: string
; 
/** Name of the role */
name?: string
; 
/** RGB color value of the role */
color?: number
; 
/** Whether the role should be displayed separately in the sidebar */
hoist?: boolean
; 
/** Whether the role can be mentioned */
mentionable?: boolean
; 
/** Reason for creating the role (appears in audit log) */
reason?: string
 };
      output: { 
/** The ID of the created role */
id: string
; 
/** Name of the role */
name: string
; 
/** RGB color value of the role */
color: number
; 
/** Whether the role is displayed separately in the sidebar */
hoist: boolean
; 
/** Position of the role in the hierarchy */
position: number
; 
/** Bitwise permissions value of the role */
permissions: string
; 
/** Whether the role can be mentioned */
mentionable: boolean
 };
    },

    /**
 * Title: Delete Channel
 * Description: Deletes a channel from a guild.
 */
    "deleteChannel": {
      input: { 
/** The ID of the channel to delete */
channelId: string
 };
      output: {  };
    },

    /**
 * Title: Delete Reaction
 * Description: Delete a reaction the current user has made for the message
 */
    "deleteOwnReaction": {
      input: { 
/** The id of the channel */
channelId: string
; 
/** The id of the message */
messageId: string
; 
/** Can be either the actual emoji or its id */
emoji: string
 };
      output: {  };
    },

    /**
 * Title: Delete Role
 * Description: Delete a role from a guild
 */
    "deleteRole": {
      input: { 
/** The ID of the guild */
guildId: string
; 
/** The ID of the role to delete */
roleId: string
; 
/** Reason for deleting the role (appears in audit log) */
reason?: string
 };
      output: {  };
    },

    /**
 * Title: End Poll
 * Description: Immediately end a poll in a channel
 */
    "endPoll": {
      input: { 
/** The ID of the channel containing the poll */
channelId: string
; 
/** The ID of the message containing the poll */
messageId: string
 };
      output: { 
/** The ID of the message with the ended poll */
messageId: string
; 
/** The poll results, null if no poll data returned */
poll: { 
/** The poll question text */
question: string
; 
/** The poll answers */
answers: Array<{ 
/** The ID of the answer */
answerId: number
; 
/** The answer text */
text: string
 }>
; 
/** When the poll expires (ISO 8601) */
expiry: string | null
; 
/** Whether users can select multiple answers */
allowMultiselect: boolean
; 
/** Vote counts per answer */
answerCounts: Array<{ 
/** The ID of the answer */
id: number
; 
/** Number of votes for this answer */
count: number
; 
/** Whether the bot voted for this answer */
meVoted: boolean
 }>
; 
/** Whether the poll results are finalized */
isFinalized: boolean
 } | null
 };
    },

    /**
 * Title: Get Channel Pins
 * Description: Returns all pinned messages in the channel.
 */
    "getChannelPins": {
      input: { 
/** The ID of the channel to retrieve pinned messages for */
channelId: string
 };
      output: { messages: Array<{ 
/** Message ID */
id: string
; 
/** Channel ID */
channelId: string
; 
/** Guild ID */
guildId?: string | null
; author: { 
/** User ID */
id: string
; 
/** Username */
username: string
; 
/** User discriminator */
discriminator: string
; 
/** Global display name */
globalName?: string | null
; 
/** User avatar hash */
avatar?: string | null
; 
/** Whether the user is a bot */
bot?: boolean
 }; 
/** Message content */
content?: string | null
; 
/** When the message was sent (ISO8601) */
timestamp: string
; 
/** Type of message */
type: number
 }> };
    },

    /**
 * Title: Get Guild
 * Description: Returns the guild object for the given ID
 */
    "getGuild": {
      input: { 
/** The ID of the guild to retrieve */
guildId: string
; 
/** When true, will return approximate member and presence counts for the guild */
withCounts: boolean
 };
      output: { 
/** Guild ID */
id: string
; 
/** Guild name */
name: string
; 
/** Icon hash */
icon: string | null
; 
/** Guild description */
description: string | null
; 
/** Splash hash */
splash: string | null
; 
/** Discovery splash hash */
discoverySplash: string | null
; 
/** Enabled guild features */
features: string[]
; 
/** Banner hash */
banner: string | null
; 
/** ID of the guild owner */
ownerId: string
; 
/** Voice region ID (deprecated) */
region?: string | null
; 
/** AFK channel ID */
afkChannelId: string | null
; 
/** AFK timeout in seconds */
afkTimeout: number
; 
/** Verification level required for the guild */
verificationLevel: number
; 
/** Default message notification level */
defaultMessageNotifications: number
; 
/** Required MFA level for the guild */
mfaLevel: number
; 
/** Explicit content filter level */
explicitContentFilter: number
; 
/** Maximum number of presences */
maxPresences?: number | null
; 
/** Maximum number of members */
maxMembers?: number
; 
/** Vanity URL code */
vanityUrlCode: string | null
; 
/** Premium tier (Server Boost level) */
premiumTier: number
; 
/** Number of boosts */
premiumSubscriptionCount?: number
; 
/** System channel ID */
systemChannelId: string | null
; 
/** System channel flags */
systemChannelFlags: number
; 
/** Rules channel ID */
rulesChannelId: string | null
; 
/** Public updates channel ID */
publicUpdatesChannelId: string | null
; 
/** Safety alerts channel ID */
safetyAlertsChannelId?: string | null
; 
/** Preferred locale */
preferredLocale: string
; 
/** Approximate number of members (only present when withCounts is true) */
approximateMemberCount?: number
; 
/** Approximate number of online members (only present when withCounts is true) */
approximatePresenceCount?: number
; roles: Array<{ 
/** The role ID */
id: string
; 
/** The role's name */
name: string
; 
/** RGB color value of the role */
color: number
; 
/** Whether the role is displayed separately in the sidebar */
hoist: boolean
; 
/** The role's position in the hierarchy */
position: number
; 
/** Bitwise permissions value of the role */
permissions: string
; 
/** Whether the role can be mentioned */
mentionable: boolean
 }> };
    },

    /**
 * Title: Get Guild Channels
 * Description: Returns a list of guild channel objects. Does not include threads.
 */
    "getGuildChannels": {
      input: { 
/** The ID of the guild to retrieve channels for */
guildId: string
 };
      output: { channels: Array<{ 
/** Channel ID */
id: string
; 
/** Channel type */
type: number
; 
/** Channel name */
name?: string
; 
/** Sorting position of the channel */
position?: number
; 
/** ID of the parent category */
parentId?: string | null
; 
/** Channel topic */
topic?: string | null
; 
/** Whether the channel is NSFW */
nsfw?: boolean
; 
/** ID of the last message sent */
lastMessageId?: string | null
 }> };
    },

    /**
 * Title: Get Guild Member
 * Description: Returns a guild member object for the specified user.
 */
    "getGuildMember": {
      input: { 
/** The ID of the guild */
guildId: string
; 
/** The ID of the user to retrieve */
userId: string
 };
      output: { user: { 
/** User ID */
id: string
; 
/** Username */
username: string
; 
/** User discriminator */
discriminator: string
; 
/** Global display name */
globalName?: string | null
; 
/** User avatar hash */
avatar?: string | null
; 
/** Whether the user is a bot */
bot?: boolean
 }; 
/** Nickname in the guild */
nick?: string | null
; 
/** Guild-specific avatar hash */
avatar?: string | null
; 
/** Array of role IDs */
roles: string[]
; 
/** When the user joined the guild (ISO8601) */
joinedAt: string
; 
/** Whether the user is deafened in voice channels */
deaf: boolean
; 
/** Whether the user is muted in voice channels */
mute: boolean
 };
    },

    /**
 * Title: getOrCreateChannelConversation
 * Description: Gets or Creates a botpress conversation from a discord channel
 */
    "getOrCreateChannelConversation": {
      input: { conversation: { 
/** The type of the discord channel */
channelType: 'dm' | 'guildText' | 'guildAnnouncement' | 'announcementThread' | 'publicThread' | 'privateThread'
; 
/** The discord channel id */
channelId: string
; 
/** The discord channel title */
channelTitle: string
; 
/** The discord guild the channel is in */
guildId?: string
 } };
      output: { 
/** The Botpress ID of the created conversation */
conversationId: string
 };
    },

    /**
 * Title: Get or Create a User
 * Description: Proactively create a user from a bot
 */
    "getOrCreateUser": {
      input: { 
/** The name of the user */
name?: string
; 
/** The URL of the user profile picture */
pictureUrl?: string
; 
/** The email of the user */
email?: string
; user: { 
/** The Discord user ID */
id: string
 } };
      output: { 
/** The Botpress ID of the created user */
userId: string
 };
    },

    /**
 * Title: List Guild Members
 * Description: Returns a list of guild member objects that are members of the guild.
 */
    "listGuildMembers": {
      input: { 
/** The ID of the guild to retrieve members for */
guildId: string
; 
/** Max number of members to return (1-1000), default 1 */
limit?: number
; 
/** The highest user id in the previous page, default "0" */
after?: string
 };
      output: { members: Array<{ user: { 
/** User ID */
id: string
; 
/** Username */
username: string
; 
/** User discriminator */
discriminator: string
; 
/** Display name */
globalName?: string | null
; 
/** Avatar hash */
avatar?: string | null
; 
/** Whether the user is a bot */
bot?: boolean
 }; 
/** Guild-specific nickname */
nick?: string | null
; 
/** Guild-specific avatar hash */
avatar?: string | null
; 
/** Array of role IDs */
roles: string[]
; 
/** When the user joined the guild (ISO8601) */
joinedAt: string
; 
/** Whether the user is deafened in voice channels */
deaf: boolean
; 
/** Whether the user is muted in voice channels */
mute: boolean
 }> };
    },

    /**
 * Title: Pin Message
 * Description: Pins a message in a channel.
 */
    "pinMessage": {
      input: { 
/** The ID of the channel containing the message */
channelId: string
; 
/** The ID of the message to pin */
messageId: string
 };
      output: {  };
    },

    /**
 * Title: Remove Member Role
 * Description: Remove a role from a guild member
 */
    "removeMemberRole": {
      input: { 
/** The ID of the guild */
guildId: string
; 
/** The ID of the user */
userId: string
; 
/** The ID of the role to remove */
roleId: string
; 
/** Reason for removing the role (appears in audit log) */
reason?: string
 };
      output: {  };
    },

    /**
 * Title: startTypingIndicator
 * Description: No description
 */
    "startTypingIndicator": {
      input: { 
/** The ID of the conversation where the typing indicator should be shown */
conversationId: string
; 
/** The message ID to which the typing indicator should be attached */
messageId: string
; 
/** The timeout in milliseconds after which the typing indicator should stop */
timeout?: number
 };
      output: {  };
    },

    /**
 * Title: stopTypingIndicator
 * Description: No description
 */
    "stopTypingIndicator": {
      input: { 
/** The ID of the conversation where the typing indicator should be removed */
conversationId: string
; 
/** The message ID from which the typing indicator should be removed */
messageId: string
 };
      output: {  };
    },

    /**
 * Title: Unban User
 * Description: Remove a ban for a user from a guild
 */
    "unbanUser": {
      input: { 
/** The ID of the guild */
guildId: string
; 
/** The ID of the user to unban */
userId: string
; 
/** Reason for the unban (appears in audit log) */
reason?: string
 };
      output: {  };
    },

    /**
 * Title: Unpin Message
 * Description: Unpins a message in a channel.
 */
    "unpinMessage": {
      input: { 
/** The ID of the channel containing the pinned message */
channelId: string
; 
/** The ID of the message to unpin */
messageId: string
 };
      output: {  };
    },
};