
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: 1.18.2
  // Integration: discord
  // Version: 1.1.0
  // File: discord\channels.ts
  // Hash: 2459abd2e0b561675ce4ccd3fb58bed92316af5a8726ab65752e2ba09625a4c5
  // Updated at: 2026-04-28T21:25:47.689Z
  ////////////////////////////////////////////////////////

  export type Integration_Channels_Discord = {
    /**
 * Title: Announcement Thread
 * Description: A guild announcement channel thread (ANNOUNCEMENT_THREAD)
 */
    "announcementThread": {
      conversation: {
        tags: {/**
 * Title: Guild ID
 * Description: The ID of the Discord guild
 */
["discord:guildId"]?: string,
/**
 * Title: Discord Channel ID
 * Description: The Discord channel ID
 */
["discord:id"]?: string,
/**
 * Title: Title
 * Description: A human-readable title for the conversation
 */
["discord:title"]?: string,
};
      };
      message: {
        tags: {/**
 * Title: Channel ID
 * Description: The Discord ID of the channel where the message was sent
 */
["discord:channelId"]?: string,
/**
 * Title: ID
 * Description: The Discord ID of the message sent
 */
["discord:id"]?: string,
/**
 * Title: Mentions Bot?
 * Description: Whether the message mentions the Discord bot
 */
["discord:mentionsBot"]?: string,
/**
 * Title: Timestamp
 * Description: The timestamp of the message
 */
["discord:ts"]?: string,
/**
 * Title: User ID
 * Description: The Discord ID of the user who sent the message
 */
["discord:userId"]?: string,
};
      };
      messages: {
"bloc": { items: Array<
{ type: 'text'; payload: { text: string } } | { type: 'image'; payload: { imageUrl: string; title?: string } } | { type: 'audio'; payload: { audioUrl: string; title?: string } } | { type: 'video'; payload: { videoUrl: string; title?: string } } | { type: 'file'; payload: { fileUrl: string; title?: string } } | { type: 'location'; payload: { latitude: number; longitude: number; address?: string; title?: string } } | { type: 'dropdown'; payload: { text: string; options: Array<{ label: string; value: string; description?: string }>; id: string } } | { type: 'choice'; payload: { title?: string; options: Array<{ label: string; value: string; style: 'primary' | 'secondary' | 'success' | 'danger' }> } } | { type: 'card'; payload: { title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }> } } | { type: 'carousel'; payload: { items: Array<{ title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }> }> } } | { type: 'rawComponents'; payload: { 
/** An array of JSON strings that represent Discord components */
components: string[]
; 
/** File URLs to attach, referenced in the components JSON as attachment://file-0.<ext>, attachment://file-1.<ext>, etc. */
fileUrls?: string[]
 } }> };

"rawComponents": { 
/** An array of JSON strings that represent Discord components */
components: string[]
; 
/** File URLs to attach, referenced in the components JSON as attachment://file-0.<ext>, attachment://file-1.<ext>, etc. */
fileUrls?: string[]
 };

"carousel": { items: Array<{ title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }> }> };

"card": { title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }> };

"choice": { title?: string; options: Array<{ label: string; value: string; style: 'primary' | 'secondary' | 'success' | 'danger' }> };

"dropdown": { text: string; options: Array<{ label: string; value: string; description?: string }>; id: string };

"location": { latitude: number; longitude: number; address?: string; title?: string };

"file": { fileUrl: string; title?: string };

"audio": { audioUrl: string; title?: string };

"video": { videoUrl: string; title?: string };

"image": { imageUrl: string; title?: string };

"text": { text: string };

      };
    },
    /**
 * Title: Direct Message
 * Description: A direct message channel with a Discord user (DM)
 */
    "dm": {
      conversation: {
        tags: {/**
 * Title: Guild ID
 * Description: The ID of the Discord guild
 */
["discord:guildId"]?: string,
/**
 * Title: Discord Channel ID
 * Description: The Discord channel ID
 */
["discord:id"]?: string,
/**
 * Title: Title
 * Description: A human-readable title for the conversation
 */
["discord:title"]?: string,
};
      };
      message: {
        tags: {/**
 * Title: Channel ID
 * Description: The Discord ID of the channel where the message was sent
 */
["discord:channelId"]?: string,
/**
 * Title: ID
 * Description: The Discord ID of the message sent
 */
["discord:id"]?: string,
/**
 * Title: Mentions Bot?
 * Description: Whether the message mentions the Discord bot
 */
["discord:mentionsBot"]?: string,
/**
 * Title: Timestamp
 * Description: The timestamp of the message
 */
["discord:ts"]?: string,
/**
 * Title: User ID
 * Description: The Discord ID of the user who sent the message
 */
["discord:userId"]?: string,
};
      };
      messages: {
"bloc": { items: Array<
{ type: 'text'; payload: { text: string } } | { type: 'image'; payload: { imageUrl: string; title?: string } } | { type: 'audio'; payload: { audioUrl: string; title?: string } } | { type: 'video'; payload: { videoUrl: string; title?: string } } | { type: 'file'; payload: { fileUrl: string; title?: string } } | { type: 'location'; payload: { latitude: number; longitude: number; address?: string; title?: string } } | { type: 'dropdown'; payload: { text: string; options: Array<{ label: string; value: string; description?: string }>; id: string } } | { type: 'choice'; payload: { title?: string; options: Array<{ label: string; value: string; style: 'primary' | 'secondary' | 'success' | 'danger' }> } } | { type: 'card'; payload: { title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }> } } | { type: 'carousel'; payload: { items: Array<{ title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }> }> } } | { type: 'rawComponents'; payload: { 
/** An array of JSON strings that represent Discord components */
components: string[]
; 
/** File URLs to attach, referenced in the components JSON as attachment://file-0.<ext>, attachment://file-1.<ext>, etc. */
fileUrls?: string[]
 } }> };

"rawComponents": { 
/** An array of JSON strings that represent Discord components */
components: string[]
; 
/** File URLs to attach, referenced in the components JSON as attachment://file-0.<ext>, attachment://file-1.<ext>, etc. */
fileUrls?: string[]
 };

"carousel": { items: Array<{ title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }> }> };

"card": { title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }> };

"choice": { title?: string; options: Array<{ label: string; value: string; style: 'primary' | 'secondary' | 'success' | 'danger' }> };

"dropdown": { text: string; options: Array<{ label: string; value: string; description?: string }>; id: string };

"location": { latitude: number; longitude: number; address?: string; title?: string };

"file": { fileUrl: string; title?: string };

"audio": { audioUrl: string; title?: string };

"video": { videoUrl: string; title?: string };

"image": { imageUrl: string; title?: string };

"text": { text: string };

      };
    },
    /**
 * Title: Guild Announcement
 * Description: A guild announcement channel (GUILD_ANNOUNCEMENT)
 */
    "guildAnnouncement": {
      conversation: {
        tags: {/**
 * Title: Guild ID
 * Description: The ID of the Discord guild
 */
["discord:guildId"]?: string,
/**
 * Title: Discord Channel ID
 * Description: The Discord channel ID
 */
["discord:id"]?: string,
/**
 * Title: Title
 * Description: A human-readable title for the conversation
 */
["discord:title"]?: string,
};
      };
      message: {
        tags: {/**
 * Title: Channel ID
 * Description: The Discord ID of the channel where the message was sent
 */
["discord:channelId"]?: string,
/**
 * Title: ID
 * Description: The Discord ID of the message sent
 */
["discord:id"]?: string,
/**
 * Title: Mentions Bot?
 * Description: Whether the message mentions the Discord bot
 */
["discord:mentionsBot"]?: string,
/**
 * Title: Timestamp
 * Description: The timestamp of the message
 */
["discord:ts"]?: string,
/**
 * Title: User ID
 * Description: The Discord ID of the user who sent the message
 */
["discord:userId"]?: string,
};
      };
      messages: {
"bloc": { items: Array<
{ type: 'text'; payload: { text: string } } | { type: 'image'; payload: { imageUrl: string; title?: string } } | { type: 'audio'; payload: { audioUrl: string; title?: string } } | { type: 'video'; payload: { videoUrl: string; title?: string } } | { type: 'file'; payload: { fileUrl: string; title?: string } } | { type: 'location'; payload: { latitude: number; longitude: number; address?: string; title?: string } } | { type: 'dropdown'; payload: { text: string; options: Array<{ label: string; value: string; description?: string }>; id: string } } | { type: 'choice'; payload: { title?: string; options: Array<{ label: string; value: string; style: 'primary' | 'secondary' | 'success' | 'danger' }> } } | { type: 'card'; payload: { title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }> } } | { type: 'carousel'; payload: { items: Array<{ title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }> }> } } | { type: 'rawComponents'; payload: { 
/** An array of JSON strings that represent Discord components */
components: string[]
; 
/** File URLs to attach, referenced in the components JSON as attachment://file-0.<ext>, attachment://file-1.<ext>, etc. */
fileUrls?: string[]
 } }> };

"rawComponents": { 
/** An array of JSON strings that represent Discord components */
components: string[]
; 
/** File URLs to attach, referenced in the components JSON as attachment://file-0.<ext>, attachment://file-1.<ext>, etc. */
fileUrls?: string[]
 };

"carousel": { items: Array<{ title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }> }> };

"card": { title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }> };

"choice": { title?: string; options: Array<{ label: string; value: string; style: 'primary' | 'secondary' | 'success' | 'danger' }> };

"dropdown": { text: string; options: Array<{ label: string; value: string; description?: string }>; id: string };

"location": { latitude: number; longitude: number; address?: string; title?: string };

"file": { fileUrl: string; title?: string };

"audio": { audioUrl: string; title?: string };

"video": { videoUrl: string; title?: string };

"image": { imageUrl: string; title?: string };

"text": { text: string };

      };
    },
    /**
 * Title: Guild Message
 * Description: A guild message channel (GUILD_TEXT)
 */
    "guildText": {
      conversation: {
        tags: {/**
 * Title: Guild ID
 * Description: The ID of the Discord guild
 */
["discord:guildId"]?: string,
/**
 * Title: Discord Channel ID
 * Description: The Discord channel ID
 */
["discord:id"]?: string,
/**
 * Title: Title
 * Description: A human-readable title for the conversation
 */
["discord:title"]?: string,
};
      };
      message: {
        tags: {/**
 * Title: Channel ID
 * Description: The Discord ID of the channel where the message was sent
 */
["discord:channelId"]?: string,
/**
 * Title: ID
 * Description: The Discord ID of the message sent
 */
["discord:id"]?: string,
/**
 * Title: Mentions Bot?
 * Description: Whether the message mentions the Discord bot
 */
["discord:mentionsBot"]?: string,
/**
 * Title: Timestamp
 * Description: The timestamp of the message
 */
["discord:ts"]?: string,
/**
 * Title: User ID
 * Description: The Discord ID of the user who sent the message
 */
["discord:userId"]?: string,
};
      };
      messages: {
"bloc": { items: Array<
{ type: 'text'; payload: { text: string } } | { type: 'image'; payload: { imageUrl: string; title?: string } } | { type: 'audio'; payload: { audioUrl: string; title?: string } } | { type: 'video'; payload: { videoUrl: string; title?: string } } | { type: 'file'; payload: { fileUrl: string; title?: string } } | { type: 'location'; payload: { latitude: number; longitude: number; address?: string; title?: string } } | { type: 'dropdown'; payload: { text: string; options: Array<{ label: string; value: string; description?: string }>; id: string } } | { type: 'choice'; payload: { title?: string; options: Array<{ label: string; value: string; style: 'primary' | 'secondary' | 'success' | 'danger' }> } } | { type: 'card'; payload: { title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }> } } | { type: 'carousel'; payload: { items: Array<{ title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }> }> } } | { type: 'rawComponents'; payload: { 
/** An array of JSON strings that represent Discord components */
components: string[]
; 
/** File URLs to attach, referenced in the components JSON as attachment://file-0.<ext>, attachment://file-1.<ext>, etc. */
fileUrls?: string[]
 } }> };

"rawComponents": { 
/** An array of JSON strings that represent Discord components */
components: string[]
; 
/** File URLs to attach, referenced in the components JSON as attachment://file-0.<ext>, attachment://file-1.<ext>, etc. */
fileUrls?: string[]
 };

"carousel": { items: Array<{ title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }> }> };

"card": { title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }> };

"choice": { title?: string; options: Array<{ label: string; value: string; style: 'primary' | 'secondary' | 'success' | 'danger' }> };

"dropdown": { text: string; options: Array<{ label: string; value: string; description?: string }>; id: string };

"location": { latitude: number; longitude: number; address?: string; title?: string };

"file": { fileUrl: string; title?: string };

"audio": { audioUrl: string; title?: string };

"video": { videoUrl: string; title?: string };

"image": { imageUrl: string; title?: string };

"text": { text: string };

      };
    },
    /**
 * Title: Private Thread
 * Description: A private thread within a forum or guild message channel (PRIVATE_THREAD)
 */
    "privateThread": {
      conversation: {
        tags: {/**
 * Title: Guild ID
 * Description: The ID of the Discord guild
 */
["discord:guildId"]?: string,
/**
 * Title: Discord Channel ID
 * Description: The Discord channel ID
 */
["discord:id"]?: string,
/**
 * Title: Title
 * Description: A human-readable title for the conversation
 */
["discord:title"]?: string,
};
      };
      message: {
        tags: {/**
 * Title: Channel ID
 * Description: The Discord ID of the channel where the message was sent
 */
["discord:channelId"]?: string,
/**
 * Title: ID
 * Description: The Discord ID of the message sent
 */
["discord:id"]?: string,
/**
 * Title: Mentions Bot?
 * Description: Whether the message mentions the Discord bot
 */
["discord:mentionsBot"]?: string,
/**
 * Title: Timestamp
 * Description: The timestamp of the message
 */
["discord:ts"]?: string,
/**
 * Title: User ID
 * Description: The Discord ID of the user who sent the message
 */
["discord:userId"]?: string,
};
      };
      messages: {
"bloc": { items: Array<
{ type: 'text'; payload: { text: string } } | { type: 'image'; payload: { imageUrl: string; title?: string } } | { type: 'audio'; payload: { audioUrl: string; title?: string } } | { type: 'video'; payload: { videoUrl: string; title?: string } } | { type: 'file'; payload: { fileUrl: string; title?: string } } | { type: 'location'; payload: { latitude: number; longitude: number; address?: string; title?: string } } | { type: 'dropdown'; payload: { text: string; options: Array<{ label: string; value: string; description?: string }>; id: string } } | { type: 'choice'; payload: { title?: string; options: Array<{ label: string; value: string; style: 'primary' | 'secondary' | 'success' | 'danger' }> } } | { type: 'card'; payload: { title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }> } } | { type: 'carousel'; payload: { items: Array<{ title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }> }> } } | { type: 'rawComponents'; payload: { 
/** An array of JSON strings that represent Discord components */
components: string[]
; 
/** File URLs to attach, referenced in the components JSON as attachment://file-0.<ext>, attachment://file-1.<ext>, etc. */
fileUrls?: string[]
 } }> };

"rawComponents": { 
/** An array of JSON strings that represent Discord components */
components: string[]
; 
/** File URLs to attach, referenced in the components JSON as attachment://file-0.<ext>, attachment://file-1.<ext>, etc. */
fileUrls?: string[]
 };

"carousel": { items: Array<{ title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }> }> };

"card": { title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }> };

"choice": { title?: string; options: Array<{ label: string; value: string; style: 'primary' | 'secondary' | 'success' | 'danger' }> };

"dropdown": { text: string; options: Array<{ label: string; value: string; description?: string }>; id: string };

"location": { latitude: number; longitude: number; address?: string; title?: string };

"file": { fileUrl: string; title?: string };

"audio": { audioUrl: string; title?: string };

"video": { videoUrl: string; title?: string };

"image": { imageUrl: string; title?: string };

"text": { text: string };

      };
    },
    /**
 * Title: Public Thread
 * Description: A public thread within a forum or guild message channel (PUBLIC_THREAD)
 */
    "publicThread": {
      conversation: {
        tags: {/**
 * Title: Guild ID
 * Description: The ID of the Discord guild
 */
["discord:guildId"]?: string,
/**
 * Title: Discord Channel ID
 * Description: The Discord channel ID
 */
["discord:id"]?: string,
/**
 * Title: Title
 * Description: A human-readable title for the conversation
 */
["discord:title"]?: string,
};
      };
      message: {
        tags: {/**
 * Title: Channel ID
 * Description: The Discord ID of the channel where the message was sent
 */
["discord:channelId"]?: string,
/**
 * Title: ID
 * Description: The Discord ID of the message sent
 */
["discord:id"]?: string,
/**
 * Title: Mentions Bot?
 * Description: Whether the message mentions the Discord bot
 */
["discord:mentionsBot"]?: string,
/**
 * Title: Timestamp
 * Description: The timestamp of the message
 */
["discord:ts"]?: string,
/**
 * Title: User ID
 * Description: The Discord ID of the user who sent the message
 */
["discord:userId"]?: string,
};
      };
      messages: {
"bloc": { items: Array<
{ type: 'text'; payload: { text: string } } | { type: 'image'; payload: { imageUrl: string; title?: string } } | { type: 'audio'; payload: { audioUrl: string; title?: string } } | { type: 'video'; payload: { videoUrl: string; title?: string } } | { type: 'file'; payload: { fileUrl: string; title?: string } } | { type: 'location'; payload: { latitude: number; longitude: number; address?: string; title?: string } } | { type: 'dropdown'; payload: { text: string; options: Array<{ label: string; value: string; description?: string }>; id: string } } | { type: 'choice'; payload: { title?: string; options: Array<{ label: string; value: string; style: 'primary' | 'secondary' | 'success' | 'danger' }> } } | { type: 'card'; payload: { title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }> } } | { type: 'carousel'; payload: { items: Array<{ title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }> }> } } | { type: 'rawComponents'; payload: { 
/** An array of JSON strings that represent Discord components */
components: string[]
; 
/** File URLs to attach, referenced in the components JSON as attachment://file-0.<ext>, attachment://file-1.<ext>, etc. */
fileUrls?: string[]
 } }> };

"rawComponents": { 
/** An array of JSON strings that represent Discord components */
components: string[]
; 
/** File URLs to attach, referenced in the components JSON as attachment://file-0.<ext>, attachment://file-1.<ext>, etc. */
fileUrls?: string[]
 };

"carousel": { items: Array<{ title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }> }> };

"card": { title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }> };

"choice": { title?: string; options: Array<{ label: string; value: string; style: 'primary' | 'secondary' | 'success' | 'danger' }> };

"dropdown": { text: string; options: Array<{ label: string; value: string; description?: string }>; id: string };

"location": { latitude: number; longitude: number; address?: string; title?: string };

"file": { fileUrl: string; title?: string };

"audio": { audioUrl: string; title?: string };

"video": { videoUrl: string; title?: string };

"image": { imageUrl: string; title?: string };

"text": { text: string };

      };
    },
  };
  