
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: 1.18.2
  // Integration: discord
  // Version: 1.1.0
  // File: discord\configurations.ts
  // Hash: 2459abd2e0b561675ce4ccd3fb58bed92316af5a8726ab65752e2ba09625a4c5
  // Updated at: 2026-04-28T21:25:47.689Z
  ////////////////////////////////////////////////////////

  export type Integration_Configurations_Discord = {
  /**
     * @title Default
     * Default configuration
     */
  default: { 
/** URL for the image used as the bot avatar (overrides Discord bot avatar) */
botAvatarUrl?: string
; 
/** Name displayed as the sender in Discord conversations (overrides Discord bot name) */
botName?: string
; 
/** Show typing indicator when bot is processing message */
typingIndicator: boolean
 };
};