
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: 1.18.2
  // Integration: discord
  // Version: 1.1.0
  // File: discord\events.ts
  // Hash: 2459abd2e0b561675ce4ccd3fb58bed92316af5a8726ab65752e2ba09625a4c5
  // Updated at: 2026-04-28T21:25:47.689Z
  ////////////////////////////////////////////////////////

  export type Integration_Events_Discord = {
    /**
 * Title: Guild Member Added
 * Description: Triggered when a user joins a guild
 */
    "guildMemberAdded": { 
/** Discord user ID of the member who joined */
userId: string
; 
/** Guild the member joined */
guildId: string
; 
/** Discord username of the member */
username: string
; 
/** ISO 8601 timestamp of when the member joined */
joinedAt: string
 };
    
    /**
 * Title: Message Poll Vote Changed
 * Description: Triggered when a user adds or removes their vote on a poll
 */
    "messagePollVoteChanged": { 
/** Discord user ID */
userId: string
; 
/** Channel containing the poll */
channelId: string
; 
/** Message containing the poll */
messageId: string
; 
/** Guild ID, absent in DMs */
guildId?: string
; 
/** ID of the answer */
answerId: number
; 
/** Whether the vote was added or removed */
action: 'add' | 'remove'
 };
    
    /**
 * Title: Reaction Changed
 * Description: Triggered when a user adds or removes a reaction on a message
 */
    "reactionChanged": { 
/** Discord user ID of the user who reacted */
userId: string
; 
/** Channel containing the message */
channelId: string
; 
/** Message that was reacted to */
messageId: string
; 
/** Guild ID, absent in DMs */
guildId?: string
; 
/** Unicode name or custom emoji name */
emojiName: string
; 
/** Custom emoji ID, absent for standard unicode emoji */
emojiId?: string
; 
/** Whether the reaction was added or removed */
action: 'add' | 'remove'
 };
    
  };
  