
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: 1.18.2
  // Integration: discord
  // Version: 1.1.0
  // File: discord/index.ts
  // Hash: 2459abd2e0b561675ce4ccd3fb58bed92316af5a8726ab65752e2ba09625a4c5
  // Updated at: 2026-04-28T21:25:47.689Z
  ////////////////////////////////////////////////////////

  import { Integration_Actions_Discord } from "./actions";
  import { Integration_Channels_Discord } from "./channels";
  import { Integration_Events_Discord } from "./events";
  import { Integration_Users_Discord } from "./users";
  import { Integration_Configurations_Discord } from "./configurations";

  export * from "./actions";
  export * from "./channels";
  export * from "./events";
  export * from "./users";
  export * from "./configurations";

  export type Integration_All_Discord = {
    actions: Integration_Actions_Discord;
    channels: Integration_Channels_Discord;
    events: Integration_Events_Discord;
    users: Integration_Users_Discord;
    configurations: Integration_Configurations_Discord;
  };
  