
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: 1.18.2
  // Integration: discord
  // Version: 1.1.0
  // File: discord/users.ts
  // Hash: 2459abd2e0b561675ce4ccd3fb58bed92316af5a8726ab65752e2ba09625a4c5
  // Updated at: 2026-04-28T21:25:47.689Z
  ////////////////////////////////////////////////////////

  export type Integration_Users_Discord = {
    tags: /**
 * Title: Discord Avatar
 * Description: The Discord avatar id
 */
"discord:avatar"
 | /**
 * Title: DM Conversation ID
 * Description: The Botpress conversation ID for the DM channel with this user
 */
"discord:dmConversationId"
 | /**
 * Title: Discord User ID
 * Description: The Discord user ID
 */
"discord:id"
 | /**
 * Title: Discord Username
 * Description: The Discord username
 */
"discord:username"
;
  };
  