
      ////////////////////////////////////////////////////////
      // DO NOT EDIT THIS FILE DIRECTLY
      // This file is auto-generated from the Botpress ADK
      // File: config.ts
      ////////////////////////////////////////////////////////

      import AgentConfigImport from "../../../agent.config";

      export const AgentConfig = AgentConfigImport;
      