
      ////////////////////////////////////////////////////////
      // DO NOT EDIT THIS FILE DIRECTLY
      // This file is auto-generated from the Botpress ADK
      // File: conversations.ts
      ////////////////////////////////////////////////////////

      import * as conversations_1 from "../../../src/conversations/discord";

      export const Conversations = {
        "discord.channel": conversations_1.default
      };
      