
      ////////////////////////////////////////////////////////
      // DO NOT EDIT THIS FILE DIRECTLY
      // This file is auto-generated from the Botpress ADK
      // File: knowledge.ts
      ////////////////////////////////////////////////////////

      

      export const Knowledge = {
        
      };
      