
      ////////////////////////////////////////////////////////
      // DO NOT EDIT THIS FILE DIRECTLY
      // This file is auto-generated from the Botpress ADK
      // File: tables.ts
      ////////////////////////////////////////////////////////

      

      export const Tables = {
        
      };
      