
      ////////////////////////////////////////////////////////
      // DO NOT EDIT THIS FILE DIRECTLY
      // This file is auto-generated from the Botpress ADK
      // File: triggers.ts
      ////////////////////////////////////////////////////////

      

      export const Triggers = {
        
      };

      // Extract trigger payload types with compiled TypeScript types
      type _TriggerPayloads = {
        
      };

      declare global {
        export type TriggerPayloads = _TriggerPayloads;
      }
      