
      ////////////////////////////////////////////////////////
      // DO NOT EDIT THIS FILE DIRECTLY
      // This file is auto-generated from the Botpress ADK
      // File: workflows.ts
      ////////////////////////////////////////////////////////

      

      export const Workflows = {
        
      };
      