/* eslint-disable */
/* tslint:disable */
// This file is generated. Do not edit it manually.
import * as addMemberRole from "./addMemberRole/index";
export * as addMemberRole from "./addMemberRole/index";
import * as addReaction from "./addReaction/index";
export * as addReaction from "./addReaction/index";
import * as banUser from "./banUser/index";
export * as banUser from "./banUser/index";
import * as callApi from "./callApi/index";
export * as callApi from "./callApi/index";
import * as createChannel from "./createChannel/index";
export * as createChannel from "./createChannel/index";
import * as createPoll from "./createPoll/index";
export * as createPoll from "./createPoll/index";
import * as createRole from "./createRole/index";
export * as createRole from "./createRole/index";
import * as deleteChannel from "./deleteChannel/index";
export * as deleteChannel from "./deleteChannel/index";
import * as deleteOwnReaction from "./deleteOwnReaction/index";
export * as deleteOwnReaction from "./deleteOwnReaction/index";
import * as deleteRole from "./deleteRole/index";
export * as deleteRole from "./deleteRole/index";
import * as endPoll from "./endPoll/index";
export * as endPoll from "./endPoll/index";
import * as getChannelPins from "./getChannelPins/index";
export * as getChannelPins from "./getChannelPins/index";
import * as getGuild from "./getGuild/index";
export * as getGuild from "./getGuild/index";
import * as getGuildChannels from "./getGuildChannels/index";
export * as getGuildChannels from "./getGuildChannels/index";
import * as getGuildMember from "./getGuildMember/index";
export * as getGuildMember from "./getGuildMember/index";
import * as getOrCreateChannelConversation from "./getOrCreateChannelConversation/index";
export * as getOrCreateChannelConversation from "./getOrCreateChannelConversation/index";
import * as getOrCreateUser from "./getOrCreateUser/index";
export * as getOrCreateUser from "./getOrCreateUser/index";
import * as listGuildMembers from "./listGuildMembers/index";
export * as listGuildMembers from "./listGuildMembers/index";
import * as pinMessage from "./pinMessage/index";
export * as pinMessage from "./pinMessage/index";
import * as removeMemberRole from "./removeMemberRole/index";
export * as removeMemberRole from "./removeMemberRole/index";
import * as startTypingIndicator from "./startTypingIndicator/index";
export * as startTypingIndicator from "./startTypingIndicator/index";
import * as stopTypingIndicator from "./stopTypingIndicator/index";
export * as stopTypingIndicator from "./stopTypingIndicator/index";
import * as unbanUser from "./unbanUser/index";
export * as unbanUser from "./unbanUser/index";
import * as unpinMessage from "./unpinMessage/index";
export * as unpinMessage from "./unpinMessage/index";

export type Actions = {
  "addMemberRole": addMemberRole.AddMemberRole;
  "addReaction": addReaction.AddReaction;
  "banUser": banUser.BanUser;
  "callApi": callApi.CallApi;
  "createChannel": createChannel.CreateChannel;
  "createPoll": createPoll.CreatePoll;
  "createRole": createRole.CreateRole;
  "deleteChannel": deleteChannel.DeleteChannel;
  "deleteOwnReaction": deleteOwnReaction.DeleteOwnReaction;
  "deleteRole": deleteRole.DeleteRole;
  "endPoll": endPoll.EndPoll;
  "getChannelPins": getChannelPins.GetChannelPins;
  "getGuild": getGuild.GetGuild;
  "getGuildChannels": getGuildChannels.GetGuildChannels;
  "getGuildMember": getGuildMember.GetGuildMember;
  "getOrCreateChannelConversation": getOrCreateChannelConversation.GetOrCreateChannelConversation;
  "getOrCreateUser": getOrCreateUser.GetOrCreateUser;
  "listGuildMembers": listGuildMembers.ListGuildMembers;
  "pinMessage": pinMessage.PinMessage;
  "removeMemberRole": removeMemberRole.RemoveMemberRole;
  "startTypingIndicator": startTypingIndicator.StartTypingIndicator;
  "stopTypingIndicator": stopTypingIndicator.StopTypingIndicator;
  "unbanUser": unbanUser.UnbanUser;
  "unpinMessage": unpinMessage.UnpinMessage;
}
