
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: 1.18.2
  // Interface: typing-indicator
  // Integrations: discord
  // Version: 0.0.3
  // File: typing_indicator\index.ts
  // Hash: ba712db3fa352dbbd35b9b05827e3f18cbf16f8cc3a27a274ba15054c00b015f
  // Updated at: 2025-12-16T19:34:19.049Z
  ////////////////////////////////////////////////////////

  import { Interface_Actions_TypingIndicator } from "./actions";

  export * from "./actions";

  export type Interface_All_TypingIndicator = {
    actions: Interface_Actions_TypingIndicator;
  };

  export const Interface_All_TypingIndicator = {
    actions: Interface_Actions_TypingIndicator,
  }
  