
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: 1.18.2
  // Interface: typing-indicator
  // Integrations: discord, webchat
  // Version: 0.0.3
  // File: typing_indicator/index.ts
  // Hash: 89e12240e243aec12a09be7107a8408701cb0245ae8689c1782cf3ab364348c2
  // Updated at: 2025-12-16T19:34:19.049Z
  ////////////////////////////////////////////////////////

  import { Interface_Actions_TypingIndicator } from "./actions";

  export * from "./actions";

  export type Interface_All_TypingIndicator = {
    actions: Interface_Actions_TypingIndicator;
  };

  export const Interface_All_TypingIndicator = {
    actions: Interface_Actions_TypingIndicator,
  }
  