
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: 1.18.2
  // Interface: llm
  // Integrations: 
  // Version: 9.0.0
  // File: llm\index.ts
  // Hash: 17bac92e1e4831775ca8faf5aefe9c0785c2f0af768aebf3e2e7a8acc7640d40
  // Updated at: 2025-12-16T19:33:56.065Z
  ////////////////////////////////////////////////////////

  export type Interface_Actions_Llm = {
    
  };

  export const Interface_Actions_Llm = {
    
  };

  