/* eslint-disable */
/* tslint:disable */
// This file is generated. Do not edit it manually.

import { z } from "@botpress/sdk";
export const output = {
  schema: z
    .object({
      id: z.string().describe("Response ID from LLM provider"),
      provider: z.string().describe("LLM provider name"),
      model: z.string().describe("Model name"),
      choices: z.array(
        z
          .object({
            type: z.default(
              z.enum(["text", "tool_calls", "tool_result", "multipart"]),
              "text",
            ),
            toolCalls: z.optional(
              z
                .array(
                  z
                    .object({
                      id: z.string(),
                      type: z.literal("function"),
                      function: z
                        .object({
                          name: z.string(),
                          arguments: z.union([
                            z
                              .record(z.string(), z.any())
                              .describe(
                                "Some LLMs may generate invalid JSON for a tool call, so this will be `null` when it happens.",
                              ),
                            z.null(),
                          ]),
                        })
                        .catchall(z.never()),
                    })
                    .catchall(z.never()),
                )
                .describe('Required if `type` is "tool_calls"'),
            ),
            toolResultCallId: z.optional(
              z.string().describe('Required if `type` is "tool_result"'),
            ),
            content: z.union([
              z
                .union([
                  z.string(),
                  z.array(
                    z
                      .object({
                        type: z.enum(["text", "image"]),
                        mimeType: z.optional(
                          z
                            .string()
                            .describe(
                              "Indicates the MIME type of the content. If not provided it will be detected from the content-type header of the provided URL.",
                            ),
                        ),
                        text: z.optional(
                          z
                            .string()
                            .describe('Required if part type is \"text\" '),
                        ),
                        url: z.optional(
                          z
                            .string()
                            .describe('Required if part type is \"image\"'),
                        ),
                      })
                      .catchall(z.never()),
                  ),
                ])
                .describe(
                  'Required unless `type` is "tool_call". If `type` is "multipart", this field must be an array of content objects. If `type` is "tool_result" then this field should be the result of the tool call (a plain string or a JSON-encoded array or object). If `type` is "tool_call" then the `toolCalls` field should be used instead.',
                ),
              z.null(),
            ]),
            role: z.literal("assistant"),
            index: z.number().int(undefined),
            stopReason: z.enum([
              "stop",
              "max_tokens",
              "tool_calls",
              "content_filter",
              "other",
            ]),
          })
          .catchall(z.never()),
      ),
      usage: z
        .object({
          inputTokens: z
            .number()
            .int(undefined)
            .describe("Number of input tokens used by the model"),
          inputCost: z
            .number()
            .describe(
              "Cost of the input tokens received by the model, in U.S. dollars",
            ),
          outputTokens: z
            .number()
            .int(undefined)
            .describe("Number of output tokens used by the model"),
          outputCost: z
            .number()
            .describe(
              "Cost of the output tokens generated by the model, in U.S. dollars",
            ),
        })
        .catchall(z.never()),
      botpress: z
        .object({
          cost: z
            .number()
            .describe("Total cost of the content generation, in U.S. dollars"),
        })
        .catchall(z.never()),
    })
    .catchall(z.never()),
};
