
////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.18.2
// Generated at: 2026-05-02T17:28:51.274Z
////////////////////////////////////////////////////////

declare module "@botpress/runtime/_types/actions" {

  export interface CallableAction<I, O> {
    (input: I): Promise<O>;
    asTool(): import("@botpress/runtime").Autonomous.Tool;
  }

  export type BotActionDefinitions = {
    "tablesRecomputeRows": {
      input: any;
      output: any;
    };
  };
  
  export type BotActions = {
    [K in keyof BotActionDefinitions]:
      CallableAction<BotActionDefinitions[K]["input"], BotActionDefinitions[K]["output"]>
  };
}
