
////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.18.2
// Generated at: 2026-05-02T17:28:51.273Z
////////////////////////////////////////////////////////

declare module "@botpress/runtime/_types/components" {
  export type CustomComponentMessage = never;
}
