
////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.18.2
// Generated at: 2026-05-02T16:22:30.064Z
////////////////////////////////////////////////////////

declare module "@botpress/runtime/_types/configuration" {
  export type Configuration = { DISCORD_BOT_TOKEN: string; DISCORD_CLIENT_ID: string; DISCORD_PUBLIC_KEY: string };
}
