
////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.18.2
// Generated at: 2026-05-02T16:22:30.067Z
////////////////////////////////////////////////////////

type Integrations = import("@botpress/runtime/_types/integrations").Integrations;
type ConversationTags = import("@botpress/runtime/_types/tags").ConversationTags;
type MessageTags = import("@botpress/runtime/_types/tags").MessageTags;

declare module "@botpress/runtime/_types/conversations" {
  export type ConversationDefinitions = {
    "discord.channel": {
      channel: "discord.channel";
      integration: "discord";
      state: { status: 'idle' | 'pending_approval' | 'ready_to_build'; pendingMermaid: string; lastValidationError: string | null; lastUserSpec: string | null };
      tags: Integrations["discord"]["channels"]["channel"]["conversation"]["tags"] & ConversationTags;
      messageTags: Integrations["discord"]["channels"]["channel"]["message"]["tags"] & MessageTags;
      messages: Integrations["discord"]["channels"]["channel"]["messages"];
      events: Integrations["discord"]["events"];
    };
  };

  /**
   * Events that can be routed to conversations (events with conversationId property).
   * Keyed by channel, containing a tuple of event names that have conversationId.
   */
  export type ConversationRoutableEvents = {
    "discord.channel": readonly [];
  };
}
