
////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.18.2
// Generated at: 2026-05-02T16:22:30.069Z
////////////////////////////////////////////////////////

type Integrations = import("@botpress/runtime/_types/integrations").Integrations;

declare module "@botpress/runtime/_types/integration-actions" {

export interface CallableAction<I, O> {
  (input: I): Promise<O>;
  asTool(): import("@botpress/runtime").Autonomous.Tool;
}

type Callable<T> = T extends { input: infer I; output: infer O }
  ? CallableAction<I, O>
  : never;

type IntegrationsMap<T> = {
  [Integration in keyof T]: T[Integration] extends { actions: infer Actions }
    ? {
        [Action in keyof Actions]: Callable<Actions[Action]>;
      }
    : never;
};

export type IntegrationActions = IntegrationsMap<Integrations>;
}
