
      ////////////////////////////////////////////////////////
      // DO NOT EDIT THIS FILE DIRECTLY
      // This file is auto-generated from the Botpress ADK
      // File: interfaces.ts
      ////////////////////////////////////////////////////////

      import { Interface_All_TypingIndicator } from "./interfaces/typing_indicator/index";
import { Interface_All_Llm } from "./interfaces/llm/index";
import { Interface_All_Listable } from "./interfaces/listable/index";

      export const Interfaces = {
        "typingIndicator": Interface_All_TypingIndicator,
"llm": Interface_All_Llm,
"listable": Interface_All_Listable
      };
      