
////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.18.2
// Generated at: 2026-05-02T17:28:51.274Z
////////////////////////////////////////////////////////

type Plugins = import("@botpress/runtime/_types/plugins").Plugins;

declare module "@botpress/runtime/_types/plugin-actions" {

export interface CallableAction<I, O> {
  (input: I): Promise<O>;
}

type Callable<T> = T extends { input: infer I; output: infer O }
  ? CallableAction<I, O>
  : never;

type PluginsMap<T> = {
  [Plugin in keyof T]: T[Plugin] extends { actions: infer Actions }
    ? {
        actions: {
          [Action in keyof Actions]: Callable<Actions[Action]>;
        };
      }
    : never;
};

export type PluginActions = PluginsMap<Plugins>;
}
