
////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.18.2
// Generated at: 2026-05-02T17:28:51.276Z
////////////////////////////////////////////////////////

declare module "@botpress/runtime/_types/channels" {
  export type Channels = "discord.announcementThread" | "discord.dm" | "discord.guildAnnouncement" | "discord.guildText" | "discord.privateThread" | "discord.publicThread" | "webchat.channel";
  export type ChannelSpec = Channels | readonly Channels[] | '*';
}

declare module "@botpress/runtime/_types/state" {
  export type BotState = { totalCompiles: number; lastCompileRequestId: string | null };
  export type UserState = {};
}
