
////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.18.2
// Generated at: 2026-05-02T16:22:30.065Z
////////////////////////////////////////////////////////

declare module "@botpress/runtime/_types/secrets" {
  export type Secrets = {
  "COMPILER_API_URL": string | undefined
  "COMPILER_API_KEY": string | undefined
  "DISCORD_BOT_TOKEN": string
  "DISCORD_CLIENT_ID": string
  "DISCORD_PUBLIC_KEY": string
};
}
