
////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.18.2
// Generated at: 2026-05-02T17:15:17.817Z
////////////////////////////////////////////////////////

declare module "@botpress/runtime/_types/secrets" {
  export type Secrets = {
  "DISCORD_BOT_TOKEN": string
  "DISCORD_CLIENT_ID": string
  "DISCORD_PUBLIC_KEY": string
};
}
