
////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.18.2
// Generated at: 2026-05-02T16:22:30.062Z
////////////////////////////////////////////////////////

declare module "@botpress/runtime/_types/state" {
  export type BotState = { totalCompiles: number; lastCompileRequestId: string | null };
  export type UserState = {};
}
