
////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.18.2
// Generated at: 2026-05-02T17:15:17.808Z
////////////////////////////////////////////////////////

declare module "@botpress/runtime/_types/tables" {
  export type TableDefinitions = {
    [key: string]: {
      Input: any;
      Output: {
        id: number;
        createdAt: string;
        updatedAt: string;
      } & any;
    };
  };
}
