
////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.18.2
// Generated at: 2026-05-02T16:22:30.038Z
////////////////////////////////////////////////////////

declare module "@botpress/runtime/_types/tags" {
  /**
   * Bot-level tags defined in agent.config.ts
   */
  export type BotTags = Record<string, string | undefined>;

  /**
   * User-level tags defined in agent.config.ts
   */
  export type UserTags = Record<string, string | undefined>;

  /**
   * Conversation-level tags defined in agent.config.ts
   */
  export type ConversationTags = {
  /**
   * ADK Sync Timestamp
   * 
   * Built-in: Last synced message timestamp. Automatically updated by the ADK when messages are processed.
   */
  adkSyncTs?: string | undefined
  /**
   * Session Expired
   * 
   * Built-in: Set to "true" when a conversation session expires via lifecycle management.
   */
  sessionExpired?: string | undefined
};

  /**
   * Message-level tags defined in agent.config.ts
   */
  export type MessageTags = {
  /**
   * Session ID
   * 
   * Built-in: ULID identifying which lifecycle session this message belongs to.
   */
  sessionId?: string | undefined
  /**
   * Session Number
   * 
   * Built-in: Session sequence number, increments each time the conversation session expires.
   */
  sessionNumber?: string | undefined
};

  /**
   * Workflow-level tags defined in agent.config.ts
   */
  export type WorkflowTags = Record<string, string | undefined>;
}
