
////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.18.2
// Generated at: 2026-05-02T17:28:51.258Z
////////////////////////////////////////////////////////

type SDKEvent = import("@botpress/client").Event;
type Events = import("@botpress/runtime/_types/events").Events;

type Event<TName extends keyof Events> = Omit<SDKEvent, "payload" | "type"> & {
  type: TName;
  payload: Events[TName];
};

declare module "@botpress/runtime/_types/triggers" {
  // Map of trigger names to their properties
  export type Triggers = {

  };
}
