// Generated workflow type definitions
// Do not edit this file directly - it will be overwritten

type WorkflowTags = import("@botpress/runtime/_types/tags").WorkflowTags;

declare module "@botpress/runtime/_types/workflows" {
  export type WorkflowDefinitions = {
    // No workflows defined yet
  };
}