
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: 1.18.2
  // Interface: listable
  // Integrations: 
  // Version: 0.0.2
  // File: listable/index.ts
  // Hash: 013e7a1cb22f4dba645b8af61f79fa04459b711c902790d2b2774a9c177a0e82
  // Updated at: 2025-12-16T19:33:52.332Z
  ////////////////////////////////////////////////////////

  export type Interface_Actions_Listable = {
    
  };

  export const Interface_Actions_Listable = {
    
  };

  